services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "5175:5175"

    volumes:
      - ./backend:/app
      - /app/node_modules

    env_file:
      - ./backend/.env
    environment:
      PORT: 5175

  frontend:
    build: ./frontend
    image: csp_frontend:1.0.0
    container_name: csp_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
