services:
  node_backend:
    build: ./backend
    image: node_backend:1.0.0
    container_name: node_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5175:5175"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    image: csp_frontend:1.0.0
    container_name: csp_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - node_backend
